coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_not_found: success

    patch:
      default:
        target: 80%
        threshold: 10%
        if_not_found: success

comment:
  layout: 'reach,diff,flags,tree,footer'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - 'tests/**/*'
  - '**/*.test.ts'
  - '**/*.spec.ts'
  - '**/*.config.*'
  - 'build/**/*'
  - '.svelte-kit/**/*'
